name: p1st company site

services:
  server:
    image: hugomods/hugo:0.123.7
    command: hugo server --config config/config.yaml,config/met-apps.yaml --bind 0.0.0.0
    volumes:
      - ./:/src
      - ~/hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313
