baseURL: https://company.p1st.app
languageCode: ja-jp
title: 株式会社プレイヤーズファースト
theme: fresh
googleAnalytics: UA-73836462-3
publishDir: "docs"
canonifyURLs: true
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  title: 株式会社プレイヤーズファースト
  # Used as meta data; describe your site to make Google Bots happy
  description: クリエイターのための月額スポンサー募集サービス「P1st」とスポーツSNSアプリ「Metシリーズ」の開発、運営を行っています。
  images:
  - /images/logos/p1st_logo_v2_320x320.png
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/p1st_logo_v2_320x320.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  googleRecaptchaKey: 6LcU1ukeAAAAADHPVVE3dpOLhFnZPOzZY1z7UZsa
  formspreeID: mayvbdpl
  formspreeAWSID: xgebrvyl
  hero:
    # Main hero title
    title: 人の輝きが世の中をより良くする
    # Hero subtitle (optional)
    subtitle: 前に進もうとする人を支える最高のサービスを提供する
    # Button text
    buttontext:
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: logos/p1st_logo_v2_320x320.png
    storyTitle: P1stのミッション
    storyDescription:
      P1st（プレイヤーズファースト）は、アスリート、ミュージシャン、アーティスト、クリエイティブな活動をしている個人など、人々の心を揺さぶる人たちの価値を高め、より良く生きていくための環境を創ります。
      将来、子どもたちが創造的な職業を安心して選べるように、世の中をより良く変えていきます。
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Services
    url: /#services
  - title: Contact
    url: /#contact
  # sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /
  section1:
    title: 事業内容
    subtitle:
    tiles:
    - title: P1st
      subtitle: パーソナルファンディングサービス
      icon: p1st_logo_v2_320x320
      text: P1stは、アスリートやクリエイティブな活動をしている個人の活動資金を募集するサービスです。月額スポンサー募集や継続的にサポーターを増やすための機能が利用できます。
      url: https://p1st.app
      buttonText: サービスサイト
    - title: フットサルメット
      subtitle: フットサルSNSアプリ
      icon: futsalmet
      text: フットサルを楽しむ人のための「フットサルSNSアプリ」。一緒に蹴れるメンバーを募集、気軽に参加、仲間を増やすなどなど、より楽しく、豊かなフットサルライフを支えます。
      url: /futsal-met
      buttonText: アプリ紹介サイト
    - title: サッカーメット
      subtitle: サッカーSNSアプリ
      icon: footballmet
      text: サッカーを楽しむ人のための「サッカーSNSアプリ」。一緒に蹴れるメンバーを募集、気軽に参加、仲間を増やすなどなど、より楽しく、豊かなフットボールライフを支えます。
      url: /football-met
      buttonText: アプリ紹介サイト
    - title: 草野球メット
      subtitle: 野球SNSアプリ
      icon: baseballmet
      text: 野球を楽しむ人のための「野球SNSアプリ」。一緒にプレーできるメンバーを募集、気軽に参加、仲間を増やすなどなど、より楽しく、豊かなベースボールライフを支えます。
      url: /baseball-met
      buttonText: アプリ紹介サイト
    - title: テニスメット
      subtitle: テニスSNSアプリ
      icon: tennismet
      text: テニスを楽しむ人のための「テニスSNSアプリ」。一緒にプレーできるメンバーを募集、気軽に参加、仲間を増やすなどなど、より楽しく、豊かなテニスライフを支えます。
      url: /met-apps
      buttonText: アプリ紹介サイト
    tiles2:
    tiles3:
    - title: JobLog ジョブログ
      subtitle: 職歴プロフィールPRサイト
      icon: joblog
      text: 職歴を登録して公開できます。あなただけの職歴プロフィールページを作ってビジネスをPRしましょう
      url: https://joblog.p1st.app/
      buttonText: サービス紹介
  section2:
    title: 業務スタイル
    subtitle: 一般的な業務形態は採用していません。「人の輝きが世の中をより良くする」コンセプトに共感し、実行できるかどうかを大事にしています。
    features:
    - title: リモートワーク
      text: オフィスを持たないフルリモートワーク。現状メンバーは、東京、青森。基本オンラインコミュニケーションです。
      # Icon (from /images/illustrations/icons/___.svg)
      icon: earth
    - title: 雇用形態はもっと自由に
      text: 正社員、契約(個人事業主や法人との)、パート・アルバイトなど形態は自由。
      icon: employment
    - title: 拘束時間なし
      text: ミッションとタスクによってドリブンさせるスタイルで、業務時間や業務規程はなし。
      icon: clock
  section3:
    title: P1st プレイヤーズファースト
    subtitle: 個人の可能性を引き上げるパーソナルファンディングサービス
    image: screenshots/top.png
    buttonText: 利用開始
    buttonLink: https://p1st.app
  section4:
    title: CEO Profile
    subtitle:
    members:
    - name: Hiro Fukami
      jpName: 深海 寛信
      quote: 元 シリコンバレースタートアップ fluxflex, inc. 共同創業者。フットサル、サッカー観戦が趣味
      job: 代表取締役社長, CEO, 創業者, Product Manager, Engineer
      img: fukami
      socialmedia:
      - link: https://www.linkedin.com/in/hirofukami
        icon: linkedin
      - link: https://twitter.com/d_sea
        icon: twitter
      - link: https://instagram.com/d_sea
        icon: instagram
      - link: https://facebook.com/fukami
        icon: facebook
  section5: true
  section6:
    title: 私たちは、社会をより豊かにするために、インターネットとソフトウエアを使う、テクノロジーカンパニーです。
    name: 株式会社プレイヤーズファースト
    address: 東京都世田谷区
    publish: 2016年3月
    ceo: 深海寛信
  section7:
    title: 沿革

  awsTraining:
    section1:
      contents:
        - title: 実践する力をつける
          subtitle: 作り上げられてこそ価値がある
          color: "#F39200"
          icon: fa-brands fa-aws
          description: AWSを単に知っているだけではなく<span class="has-text-weight-bold">「操作してシステムを作り上げること」</span>を重視したカリキュラムです。
        - title: AWS主要機能を網羅
          subtitle: よく利用するサービスを確実に理解する
          color: "#23d160"
          icon: fa-solid fa-table
          description: 数あるAWSのサービスから、現場でよく利用されるものに対して確実に理解を深め、実践演習を行います。
        - title: 現場を想定した演習課題
          subtitle: 要件に対して正しく構築して説明する
          color: "#209cee"
          icon: fa-solid fa-person-chalkboard
          description: 課題の要件を満たすようにAWSで構築し、その成果をプレゼンテーションしていただきます。
        - title: カスタマイズ
          subtitle: 最適なアプローチが最も早く成長できます
          color: "#3273dc"
          icon: fa-solid fa-arrow-up-right-dots
          description: 研修内容のカスタマイズにも対応しています。開催日程や期間も柔軟に対応できます。
    section2:
      contents:
        - title: 研修の専門家ではなくプロダクト開発を行っているから
          description: 研修の専門家は現場の経験が乏しくなり、<span class="has-text-weight-bold">実際にはどう使われているのかの情報が研修に反映されにくくなります</span>。どうしても知識中心、講義中心になる傾向があります。
        - title: AWS資格取得だけではない実践研修だから
          description: また、AWS資格取得を主目的とすると、暗記中心の実践力の乏しい研修となり、資格を有していて現場で対応できずに顧客からの信頼を損ねることがあります。
        - title: プロダクト開発と運営を長年継続しているから
          description: 弊社は自社サービスの開発・運営で培った長年の経験をもとに、<span class="has-text-weight-bold">実際に現場で使っているAWSの利用方法や求められる要件を知っています</span>。
    section3:
      contents:
        - title: EC2
          description: "<p>あるWebシステムをAWS上で構築します。顧客から以下の要望を提示されました。要望を満たすEC2の設定を行ってください。</p>
                <ul>
                  <li>Webサーバーは起動時に最新のソースをデプロイしてほしい。Git利用</li>
                  <li>Webサーバーは port 8080 番でリッスン。MySQL port 3306 に接続</li>
                  <li>監視はできるだけ頻度高く、多くの項目をモニターしたい</li>
                  <li>
                    Webサーバーは複数台で分散しAuto Scaling利用予定、適切なEC2インスタンスタイプとスペックの提案
                  </li>
                </ul>"
        - title: IAM
          description: "<p>AWSを用いたシステムで以下の利用者を想定しています。IAMを使ってそれぞれ適切なユーザー・グループを作成してください。</p>
                <ul>
                  <li>顧客 : 支払者、システム管理者</li>
                  <li>ソフトウエア開発会社 : デプロイするソースコードを納品、インフラの設定は行わない</li>
                  <li>インフラ事業者 : インフラ構築の外注先</li>
                  <li>システム運用事業者 : システム運用・障害対応・監視を行う外注先</li>
                </ul>"
        - title: オートスケーリング
          description: "<p>Auto Scaling を使って EC2 がスケールアウト・スケールインする環境を構築してください。</p>
                <p>なるべく「落ちない環境」を実現するための設定をしてみてください。</p>
                <p>発表時にスケーリングのデモができるよう、閾値の内容を考慮してください。</p>"
    section4:
      contents:
        - title: AWS資格取得
          description: '<p>研修期間内に以下の資格を取得</p>
              <div class="tag">テクニカルプロフェッショナル</div>
              <div class="tag">ビジネスプロフェッショナル</div>
              <div class="tag">クラウドプラクティショナー</div>
              <div class="tag">ソリューションアーキテクト アソシエイト</div>'
        - title: 課題演習
          description: '<p>対象AWSサービス</p>
                <span class="tag">IAM</span>
                <span class="tag">EC2</span>
                <span class="tag">S3</span>
                <span class="tag">VPC</span>
                <span class="tag">ELB</span>
                <span class="tag">RDS</span>
                <span class="tag">Route53</span>
                <span class="tag">CloudFront</span>
                <span class="tag">SNS/SES</span>
                <span class="tag">Lambda</span>
                <span class="tag">CloudFormation</span>'
        - title: 最終課題演習
          description: '<p>一般的な LAMP + AutoScaling 構成を構築</p>
                <p>顧客への成果物としてシステム構成図の作成、動作確認のデモをプレゼンテーションを実施</p><p>講師からプレゼンテーションに対するフィードバックを行う。</p>'
    section5:
      books:
        - title: 2023年「ひとりスタートアップ」
        - title: 2014年「WordPressプロフェッショナル養成読本」技術評論社 AWSの章を担当
        - title: 2010年「よくわかるAmazonEC2/S3入門」技術評論社
      works:
        - title: 東証一部上場企業などのエンジニア育成のための研修・講義の実績あり
        - title: SES企業 エンジニア向け AWS資格取得＆実践研修
        - title: NTTグループ企業 エンジニア向け Chef実践研修
        - title: NTTグループ企業 エンジニア勉強会講師
    section6:
      plans:
        - title: 演習課題 1日
          term: 1日間 (8時間/日)
          description: '現場で求められる要件を想定した演習課題から最終演習課題のみ実施<br>AWSの設定・システム構築後、成果発表<br>成果物と発表内容への講師レビュー<br>演習課題数: 1'
          number: 5〜20名
          targets:
            - content: AWS主要サービスの理解があること
            - content: Linux、データベース、インターネットへの基本的な理解ができていること
          price: 168,000円
        - title: 演習課題 主要サービス対象
          term: 3日間 (8時間/日)
          description: '現場で求められる要件を想定した主要AWSサービスへの演習課題の実施<br>AWSの設定・システム構築後、成果発表<br>成果物と発表内容への講師レビュー<br>演習課題数: 10程度(当日の進み具合によって前後します)'
          number: 5〜30名
          targets:
            - content: AWS主要サービスの理解があること
            - content: Linux、データベース、インターネットへの基本的な理解ができていること
          price: 418,000円
        - title: AWS主要サービス講義 + 演習課題
          term: 20日間 (4週間 8時間/日)
          description: 'AWS主要サービス講義の実施<br>現場で求められる要件を想定した演習課題の実施<br>AWSの設定・システム構築後、成果発表<br>成果物と発表内容への講師レビュー<br>演習課題数: 15程度(当日の進み具合によって前後します)'
          number: 5〜40名
          price: 194万円
          targets:
            - content: Linux、データベース、インターネットへの基本的な理解ができていること

  footer:
    # Logo (from /images/logos/___)
    logo: p1st_logo_v2_320x320.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://twitter.com/pys1st
      icon: twitter
    - link: https://www.instagram.com/players1st.web/
      icon: instagram
    - link: https://youtube.com/@p1st
      icon: youtube-play
    - link: https://www.facebook.com/players1st.web
      icon: facebook
    bulmalogo: false
    quicklinks:
      column1:
        title: "Services"
        links:
        - text: P1st
          link: https://p1st.app
        - text: フットサルメット
          link: /futsal-met
        - text: サッカーメット
          link: /football-met
        - text: 草野球メット
          link: /baseball-met
        - text: テニスメット
          link: /met-apps
